/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaGradle;

public class App {
    public String getGreeting() {
        return "Hello Worldxxxx!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        FileAction fileAction = new FileAction();
        // fileAction.readFile();
        // fileAction.writeFile("hola clase, como están");
        // fileAction.deleteFile();
        DatabaseAction databaseAction = new DatabaseAction();
        databaseAction.getData();
    }
}
